Fix broken "poedit -a" on files with obsolete entries.
Group obsolete entries together at the end of produced file, so that potool can
ingest it back successfully.  Also add a regression test for poedit.

diff --git a/scripts/poedit b/scripts/poedit
--- a/scripts/poedit
+++ b/scripts/poedit
@@ -88,9 +88,11 @@ fi
 
 if [ "$INCLUDE_ALL_MSGS" = "yes" ]
 then
-	potool "$POFILE" -ft > "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -ft > \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
+	potool "$POFILE" -ft -fno > "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -ft -fno > \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
 	echo >> "$TMPFILE"
 	potool "$POFILE" -fnt >> "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -fnt >> \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
+	echo >> "$TMPFILE"
+	potool "$POFILE" -ft -fo >> "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -ft -fo >> \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
 else
 	potool "$POFILE" -fnth > "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -fnth > \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
 fi
