Added exit code checks to poedit, for potool and $EDITOR invocations. Also improved some error messages.

diff --git a/scripts/poedit b/scripts/poedit
--- a/scripts/poedit
+++ b/scripts/poedit
@@ -83,11 +83,11 @@ fi
 
 if [ "$INCLUDE_ALL_MSGS" = "yes" ]
 then
-	potool "$POFILE" -ft > "$TMPFILE"
+	potool "$POFILE" -ft > "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -ft > \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
 	echo >> "$TMPFILE"
-	potool "$POFILE" -fnt >> "$TMPFILE"
+	potool "$POFILE" -fnt >> "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -fnt >> \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
 else
-	potool "$POFILE" -fnth > "$TMPFILE"
+	potool "$POFILE" -fnth > "$TMPFILE" || { echo "Running 'potool \"$POFILE\" -fnth > \"$TMPFILE\"' failed with code $?" >&2; exit 1; }
 fi
 
 if [ $IGNORE_ENCODING = no ] ; then
@@ -97,7 +97,7 @@ if [ $IGNORE_ENCODING = no ] ; then
 	iconv -f "$input_encoding" -t "$locale_encoding" < "$TMPFILE" > "$TMPFILE2"
 	if [ $? -ne 0 ]; then
 		echo "Recoding from [$input_encoding] to [$locale_encoding] failed." 1>&2
-		echo "Temp. file: " $TMPFILE 1>&2
+		echo "Temp. file: $TMPFILE" 1>&2
 		exit 1
 	fi
 	
@@ -108,6 +108,7 @@ if [ $IGNORE_ENCODING = no ] ; then
 	if [ $? -ne 0 ]; then
 		echo "Failed to substitute the encoding attribute in the header." 1>&2
 		echo "Make sure the file has a proper header before running $0" 1>&2
+		echo "Temp. file: $TMPFILE2" 1>&2
 		exit 1
 	fi
 fi
@@ -116,6 +117,12 @@ fi
 # Run editor and update the file on success
 #
 $EDITOR "$TMPFILE"
+editor_ret="$?"
+
+if [ $editor_ret -ne 0 ]; then
+	echo "$EDITOR exited abnormally (code $editor_ret), not updating the po file" 1>&2
+	exit 1
+fi
 
 if [ $IGNORE_ENCODING = no ] ; then
 	#
@@ -134,24 +141,20 @@ if [ $IGNORE_ENCODING = no ] ; then
 	iconv -f "$locale_encoding" -t "$input_encoding" < "$TMPFILE2" > "$TMPFILE"
 	if [ $? -ne 0 ]; then
 		echo "Recoding back from [$locale_encoding] to [$input_encoding] failed." 1>&2
-		echo "Temp. file: " $TMPFILE 1>&2
+		echo "Temp. file: " $TMPFILE2 1>&2
 		exit 1
 	fi
 fi
 
+mv "$POFILE" "$POFILE~" || { echo "Failed to rename \"$POFILE\" to \"$POFILE~\""; exit 1; }
+potool "$POFILE~" "$TMPFILE" > "$POFILE"
 if [ $? -eq 0 ]; then
-	mv "$POFILE" "$POFILE~"
-	potool "$POFILE~" "$TMPFILE" > "$POFILE" 
-	if [ $? -eq 0 ]; then
-		printf "Before: %s/%s\n" `potool -ft -s "$POFILE~"` `potool -s "$POFILE~"` 
-		printf "After:  %s/%s\n" `potool -ft -s "$POFILE"` `potool -s "$POFILE"` 
-		rm -f "$POFILE~" "$TMPFILE"
-	else
-		mv -f "$POFILE~" "$POFILE"
-		echo "Temp. file: " $TMPFILE
-	fi
+	printf "Before: %s/%s\n" `potool -ft -s "$POFILE~"` `potool -s "$POFILE~"`
+	printf "After:  %s/%s\n" `potool -ft -s "$POFILE"` `potool -s "$POFILE"`
+	rm -f "$POFILE~" "$TMPFILE"
 else
-	echo $EDITOR exited abnormally, not updating the po file
+	mv -f "$POFILE~" "$POFILE"
+	echo "Merging $POFILE with $TMPFILE failed" >&2
 	exit 1
 fi
 
